version: '3'

services:
  laravel:
    build:
      context: .
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/docker.env:/var/www/.env
      - node:/var/www/node_modules # exclude node_modules but persist them
    networks:
      - ajutam
    ports:
      - '8000:8000'
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    networks:
      - ajutam

  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    networks:
      - ajutam
    environment:
      MYSQL_DATABASE: laravue
      MYSQL_USER: laravue
      MYSQL_PASSWORD: laravue
      MYSQL_ROOT_PASSWORD: root

networks:
  ajutam:
    driver: bridge

volumes:
  node:
